import io
import os
import sys
import tempfile
from pathlib import Path
from PIL import Image

import torch
from flask import Flask, jsonify, request, send_from_directory
from flask_cors import CORS
from ultralytics import YOLO

# ==========================================
# PROJECT PATHS & MODULE IMPORTS
# ==========================================
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR / "frontend"

# Model path: check standard models directory first, fallback to runs directory
PRIMARY_MODEL_PATH = BASE_DIR / "models" / "best.pt"
FALLBACK_MODEL_PATH = (
    BASE_DIR
    / "runs"
    / "classify"
    / "runs"
    / "classify"
    / "crop_disease_classifier_v4-2"
    / "weights"
    / "best.pt"
)
MODEL_PATH = PRIMARY_MODEL_PATH if PRIMARY_MODEL_PATH.exists() else FALLBACK_MODEL_PATH

# Import helper modules
sys.path.insert(0, str(BASE_DIR))
sys.path.insert(0, str(BASE_DIR / "backend"))

from serpapi_search import search_agriculture, search_agricultural_intelligence
from disease_knowledge import (
    DISEASE_KNOWLEDGE,
    SUPPORTED_CROPS,
    VISION_MODEL_SUPPORTED_CROPS,
    EXPANDED_KNOWLEDGE_CROPS,
    ALL_KNOWLEDGE_CROPS,
    UNSUPPORTED_CROPS_EXAMPLES,
    get_disease_info,
    is_vision_model_supported,
)

# ==========================================
# FLASK APPLICATION SETUP
# ==========================================
app = Flask(__name__, static_folder=str(FRONTEND_DIR), static_url_path="")
CORS(app)

# Max upload limit (15 MB)
app.config["MAX_CONTENT_LENGTH"] = 15 * 1024 * 1024

# ==========================================
# DEVICE CONFIGURATION (RTX 3050 4GB GPU / CPU)
# ==========================================
if torch.cuda.is_available():
    DEVICE = "cuda:0"
    DEVICE_NAME = torch.cuda.get_device_name(0)
    print(f"[AgriIntel] CUDA GPU detected: {DEVICE_NAME} ({DEVICE})")
else:
    DEVICE = "cpu"
    DEVICE_NAME = "CPU"
    print("[AgriIntel] Running on CPU device.")

# ==========================================
# LOAD YOLO CLASSIFICATION MODEL
# ==========================================
print(f"[AgriIntel] Loading YOLO classifier from: {MODEL_PATH}")
if not MODEL_PATH.exists():
    raise FileNotFoundError(f"Model checkpoint not found at {MODEL_PATH}")

try:
    model = YOLO(str(MODEL_PATH))
    # Warm-up / verify model names
    NUM_CLASSES = len(model.names)
    print(f"[AgriIntel] Model loaded successfully with {NUM_CLASSES} classes.")
except Exception as exc:
    print(f"[AgriIntel] Fatal error loading model: {exc}")
    raise

# Group supported classes by crop for client discovery
CROPS_TO_CLASSES = {}
for cls_idx, cls_name in model.names.items():
    if "___" in cls_name:
        crop_part, cond_part = cls_name.split("___", 1)
    else:
        crop_part, cond_part = cls_name, cls_name
    CROPS_TO_CLASSES.setdefault(crop_part, []).append({
        "id": cls_idx,
        "class_name": cls_name,
        "condition": cond_part,
        "condition_display": cond_part.replace("_", " ").strip()
    })

# ==========================================
# HELPER FUNCTIONS
# ==========================================
def get_crop_name(class_name: str) -> str:
    if "___" in class_name:
        return class_name.split("___", 1)[0]
    return class_name


def get_condition_name(class_name: str) -> str:
    if "___" in class_name:
        return class_name.split("___", 1)[1]
    return class_name


def clean_display_name(text: str) -> str:
    clean = str(text or "").replace("_", " ").replace("  ", " ").strip()
    if clean.lower() == "corn (maize)":
        return "Corn (Maize)"
    if clean.lower() == "pepper, bell":
        return "Bell Pepper"
    if clean.lower() == "cherry (including sour)":
        return "Cherry"
    return clean


def confidence_level(confidence: float) -> str:
    if confidence >= 0.80:
        return "high"
    if confidence >= 0.60:
        return "medium"
    return "low"


# Standard agricultural preliminary disclaimer
PRELIMINARY_DISCLAIMER = (
    "Preliminary AI Diagnosis: This detection is generated by automated computer vision and "
    "should not replace an in-person inspection by a certified agricultural extension officer, "
    "plant pathologist, or local Krishi Vigyan Kendra (KVK) expert. Do not apply synthetic chemical "
    "pesticides or commercial treatments based solely on an AI prediction."
)

REJECTION_MESSAGE_UNSUPPORTED = (
    "This image may belong to a crop or condition outside the model's 16 supported classes "
    "(such as Cotton, Chilli, Groundnut, Mango, Banana, or Pigeon pea). "
    "Please upload a clearer leaf image of a supported crop, or consult a local agricultural extension officer."
)

# ==========================================
# FRONTEND STATIC ROUTES
# ==========================================
@app.route("/", methods=["GET"])
def index():
    """Serve AgriIntel Frontend Homepage."""
    return send_from_directory(app.static_folder, "index.html")


@app.route("/<path:filename>", methods=["GET"])
def serve_static(filename):
    """Serve static frontend assets (CSS, JS, images)."""
    return send_from_directory(app.static_folder, filename)


# ==========================================
# API ENDPOINT: HEALTH CHECK
# ==========================================
@app.route("/api/health", methods=["GET"])
def health():
    """
    Return comprehensive application status, model status,
    class count, device information and memory state.
    """
    cuda_available = torch.cuda.is_available()
    cuda_mem = {}
    if cuda_available and DEVICE.startswith("cuda"):
        try:
            allocated = round(torch.cuda.memory_allocated(0) / (1024 ** 2), 2)
            reserved = round(torch.cuda.memory_reserved(0) / (1024 ** 2), 2)
            cuda_mem = {"allocated_mb": allocated, "reserved_mb": reserved}
        except Exception:
            pass

    return jsonify({
        "success": True,
        "status": "online",
        "service": "AgriIntel AI Crop Intelligence",
        "model_loaded": True,
        "model_path": str(MODEL_PATH),
        "device": DEVICE,
        "device_name": DEVICE_NAME,
        "cuda_available": cuda_available,
        "cuda_memory": cuda_mem,
        "classes_count": NUM_CLASSES,
        "supported_crops_count": len(SUPPORTED_CROPS),
        "supported_crops": SUPPORTED_CROPS,
        "unsupported_examples": UNSUPPORTED_CROPS_EXAMPLES,
    })


# ==========================================
# API ENDPOINT: CLASSES & SCOPE
# ==========================================
@app.route("/api/classes", methods=["GET"])
def get_classes():
    """
    Return all 54 vision model classes, 79 knowledge base profiles across 22 crops,
    and transparent documentation of supported vs queued crops.
    """
    # Build complete knowledge catalog with vision-trained flags
    knowledge_catalog = []
    for cls_name, info in DISEASE_KNOWLEDGE.items():
        knowledge_catalog.append({
            "crop": info.get("crop", ""),
            "crop_display": info.get("crop_display", info.get("crop", "")),
            "class_name": cls_name,
            "condition": info.get("condition", ""),
            "condition_display": info.get("condition", ""),
            "pathogen": info.get("pathogen", "Not specified"),
            "is_healthy": info.get("is_healthy", False),
            "is_vision_trained_v4": info.get("model_trained_v4", True),
            "severity": info.get("severity", "Moderate"),
            "description": info.get("description", ""),
            "symptoms": info.get("symptoms", []),
            "recommended_next_steps": info.get("recommended_next_steps", []),
            "preventive_practices": info.get("preventive_practices", [])
        })

    return jsonify({
        "success": True,
        "total_classes": NUM_CLASSES,
        "classes": [model.names[i] for i in range(NUM_CLASSES)],
        "crops": CROPS_TO_CLASSES,
        "vision_model_crops": VISION_MODEL_SUPPORTED_CROPS,
        "expanded_knowledge_crops": EXPANDED_KNOWLEDGE_CROPS,
        "all_knowledge_crops": ALL_KNOWLEDGE_CROPS,
        "supported_crops": SUPPORTED_CROPS,
        "unsupported_crops_examples": UNSUPPORTED_CROPS_EXAMPLES,
        "guidance_database_count": len(DISEASE_KNOWLEDGE),
        "knowledge_catalog": knowledge_catalog,
    })


# ==========================================
# API ENDPOINT: DIAGNOSE CROP IMAGE
# ==========================================
@app.route("/api/diagnose", methods=["POST"])
def diagnose():
    """
    Accepts multipart image upload, preprocesses, performs YOLO inference,
    evaluates confidence and crop uncertainty, and returns top-3 predictions
    along with verified agricultural guidance and optional references.
    """
    if "image" not in request.files:
        return jsonify({"success": False, "error": "No image file provided in upload."}), 400

    uploaded_file = request.files["image"]
    if not uploaded_file or uploaded_file.filename == "":
        return jsonify({"success": False, "error": "No image file selected."}), 400

    # Optional crop hint provided by user (e.g. 'Paddy', 'Cotton', 'Auto-detect')
    crop_hint = request.form.get("crop_hint", "").strip()

    # Validate file extension
    filename = uploaded_file.filename.lower()
    allowed_exts = {".jpg", ".jpeg", ".png", ".webp"}
    file_ext = Path(filename).suffix
    if file_ext not in allowed_exts:
        return jsonify({
            "success": False,
            "error": f"Unsupported file extension '{file_ext}'. Allowed formats: JPG, JPEG, PNG, WebP."
        }), 400

    # Read bytes safely into PIL Image
    try:
        image_bytes = uploaded_file.read()
        if len(image_bytes) == 0:
            return jsonify({"success": False, "error": "Uploaded image file is empty."}), 400

        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    except Exception as exc:
        app.logger.warning("Failed to parse uploaded image: %s", exc)
        return jsonify({"success": False, "error": "Corrupted or invalid image file."}), 400

    width, height = image.size
    image_warnings = []
    if width < 224 or height < 224:
        image_warnings.append(
            f"Image resolution ({width}x{height}) is lower than the recommended 224x224. "
            "For highest diagnostic precision, upload a clear, high-resolution leaf photo."
        )

    # Check for crop hint status: vision-trained vs expanded knowledge
    is_hint_expanded = False
    is_hint_unsupported = False
    hint_matched_name = None

    if crop_hint and crop_hint.lower() not in {"auto", "auto-detect", ""}:
        for exp_crop in EXPANDED_KNOWLEDGE_CROPS:
            if exp_crop.lower() in crop_hint.lower():
                is_hint_expanded = True
                hint_matched_name = exp_crop
                break
        if not is_hint_expanded and not is_vision_model_supported(crop_hint):
            is_hint_unsupported = True
            hint_matched_name = crop_hint

    # Perform YOLO Inference with GPU memory safeguards & CPU fallback
    global DEVICE
    inference_device = DEVICE
    try:
        with torch.no_grad():
            results = model.predict(source=image, device=inference_device, verbose=False)
    except torch.cuda.OutOfMemoryError:
        app.logger.warning("CUDA Out of Memory encountered! Switching to CPU fallback.")
        torch.cuda.empty_cache()
        inference_device = "cpu"
        with torch.no_grad():
            results = model.predict(source=image, device="cpu", verbose=False)
    except Exception as exc:
        app.logger.exception("Model prediction failed: %s", exc)
        # Attempt fallback to CPU
        try:
            with torch.no_grad():
                results = model.predict(source=image, device="cpu", verbose=False)
        except Exception as cpu_exc:
            return jsonify({
                "success": False,
                "error": f"Inference engine failed to analyze image: {str(cpu_exc)}"
            }), 500

    result = results[0]
    probabilities = result.probs
    top1_index = int(probabilities.top1)
    top1_confidence = float(probabilities.top1conf)
    top1_class_name = str(model.names[top1_index])

    # Extract Top-3 predictions
    top_predictions = []
    top_indices = probabilities.top5[:3] if hasattr(probabilities, "top5") else [top1_index]
    for idx in top_indices:
        idx = int(idx)
        cls_name = str(model.names[idx])
        conf_val = float(probabilities.data[idx])
        c_crop = get_crop_name(cls_name)
        c_cond = get_condition_name(cls_name)
        top_predictions.append({
            "class_name": cls_name,
            "crop": c_crop,
            "crop_display": clean_display_name(c_crop),
            "condition": c_cond,
            "condition_display": clean_display_name(c_cond),
            "confidence": round(conf_val * 100, 1),
            "confidence_level": confidence_level(conf_val)
        })

    primary_crop = get_crop_name(top1_class_name)
    primary_condition = get_condition_name(top1_class_name)
    crop_display = clean_display_name(primary_crop)
    condition_display = clean_display_name(primary_condition)
    confidence_pct = round(top1_confidence * 100, 1)
    level = confidence_level(top1_confidence)

    # ==========================================
    # UNCERTAINTY & REJECTION MECHANISM
    # ==========================================
    is_uncertain = False
    rejection_reason = None
    rejection_message = None

    if is_hint_expanded:
        is_uncertain = True
        rejection_reason = f"Crop '{hint_matched_name}' is in Knowledge Base & Search; vision model v5 training is queued."
        rejection_message = (
            f"Notice: '{hint_matched_name}' is available in AgriIntel's Knowledge Base & Live Agricultural Search ({len(DISEASE_KNOWLEDGE)} conditions across {len(ALL_KNOWLEDGE_CROPS)} crops). "
            f"However, image-based neural detection for {hint_matched_name} is currently queued in the v5 training pipeline. "
            f"The v4.2 vision model was trained on 16 crops (Apple, Blueberry, Cherry, Corn, Grape, Orange, Paddy, Peach, Bell Pepper, Potato, Raspberry, Soybean, Squash, Strawberry, Tomato, Wheat)."
        )
    elif is_hint_unsupported:
        is_uncertain = True
        rejection_reason = f"Crop '{hint_matched_name}' is not supported by the model."
        rejection_message = (
            f"Notice: '{hint_matched_name}' is outside AgriIntel's current 16 vision-supported crops. "
            f"Please consult a local agricultural officer or KVK for {hint_matched_name} diagnosis."
        )
    elif top1_confidence < 0.45:
        is_uncertain = True
        rejection_reason = "Low model confidence (< 45%)."
        rejection_message = REJECTION_MESSAGE_UNSUPPORTED
    elif len(top_predictions) >= 2:
        top1_crop = top_predictions[0]["crop"]
        top2_crop = top_predictions[1]["crop"]
        top1_score = top_predictions[0]["confidence"]
        top2_score = top_predictions[1]["confidence"]
        # Disparate crops with margin < 15% and neither > 65%
        if top1_crop != top2_crop and (top1_score - top2_score) < 15.0 and top1_score < 65.0:
            is_uncertain = True
            rejection_reason = "Ambiguous prediction between multiple different crops."
            rejection_message = REJECTION_MESSAGE_UNSUPPORTED

    # ==========================================
    # RETRIEVE VERIFIED AGRICULTURAL GUIDANCE
    # ==========================================
    disease_info = get_disease_info(top1_class_name)
    if disease_info is None:
        # Fallback when exact guidance is missing
        is_healthy = primary_condition.lower() in {"healthy", "normal"}
        disease_info = {
            "crop": primary_crop,
            "crop_display": crop_display,
            "condition": condition_display,
            "pathogen": "Not specified",
            "is_healthy": is_healthy,
            "severity": "None" if is_healthy else "Unknown",
            "description": (
                f"The model classified this plant as {condition_display} on {crop_display}. "
                "Guidance not available for this condition yet."
            ),
            "symptoms": [
                "Guidance not available for this condition yet in the verified knowledge base.",
                "Compare the plant against official agricultural extension literature."
            ],
            "recommended_next_steps": [
                "Inspect multiple plants across the plot to establish symptom consistency.",
                "Consult a qualified agricultural extension officer or local KVK before taking action."
            ],
            "preventive_practices": [
                "Follow standard sanitation and balanced crop nutrition practices."
            ]
        }

    # ==========================================
    # OPTIONAL INTEGRATED AGRICULTURAL SEARCH
    # ==========================================
    agricultural_sources = []
    # Trigger search automatically if requested or if disease is confirmed & confidence is fair
    include_search = request.form.get("include_search", "true").lower() == "true"
    if include_search and not disease_info.get("is_healthy", False) and not is_uncertain:
        try:
            agricultural_sources = search_agriculture(
                disease_name=condition_display,
                crop_name=crop_display
            ) or []
        except Exception as exc:
            app.logger.warning("SerpApi search during diagnose failed: %s", exc)
            agricultural_sources = []

    # Clean up PyTorch GPU memory if on CUDA
    if torch.cuda.is_available() and DEVICE.startswith("cuda"):
        torch.cuda.empty_cache()

    return jsonify({
        "success": True,
        "image_warning": " ".join(image_warnings) if image_warnings else None,
        "prediction": {
            "class_name": top1_class_name,
            "crop": primary_crop,
            "crop_display": crop_display,
            "condition": primary_condition,
            "condition_display": condition_display,
            "confidence": confidence_pct,
            "confidence_level": level,
        },
        "top_predictions": top_predictions,
        "uncertainty": {
            "is_uncertain": is_uncertain,
            "rejection_reason": rejection_reason,
            "rejection_message": rejection_message,
        },
        "information": disease_info,
        "disclaimer": PRELIMINARY_DISCLAIMER,
        "agricultural_sources": agricultural_sources,
    })


# ==========================================
# API ENDPOINT: AGRICULTURAL RESEARCH / SERPAPI
# ==========================================
@app.route("/api/agricultural-search", methods=["POST"])
def agricultural_search_endpoint():
    """
    Search agricultural intelligence (symptoms, prevention, IPM,
    official extension advisories) through SerpApi.
    Accepts JSON or Form-data: { crop, disease, query, category }
    """
    data = request.get_json(silent=True) or request.form

    crop = data.get("crop", "").strip()
    disease = data.get("disease", "").strip()
    query = data.get("query", "").strip()
    category = data.get("category", "all").strip()

    try:
        search_result = search_agricultural_intelligence(
            crop_name=crop,
            disease_name=disease,
            query=query,
            category=category
        )
        return jsonify(search_result)
    except Exception as exc:
        app.logger.exception("Agricultural search endpoint error: %s", exc)
        return jsonify({
            "success": False,
            "sources": [],
            "message": f"Search failed: {str(exc)}"
        }), 500


# ==========================================
# SERVER ENTRYPOINT
# ==========================================
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print("\n" + "=" * 50)
    print("      🌱 AGRIINTEL INTELLIGENCE SYSTEM")
    print("=" * 50)
    print(f"Device:    {DEVICE_NAME} ({DEVICE})")
    print(f"Model:     {MODEL_PATH}")
    print(f"Classes:   {NUM_CLASSES} across {len(SUPPORTED_CROPS)} crops")
    print(f"Knowledge: {len(DISEASE_KNOWLEDGE)} verified disease profiles")
    print(f"Web UI:    http://127.0.0.1:{port}")
    print(f"Health:    http://127.0.0.1:{port}/api/health")
    print("=" * 50 + "\n")
    app.run(host="127.0.0.1", port=port, debug=False)
